/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestorestoques;

import java.awt.Color;

/**
 *
 * @author Ericz
 */
public class movimentacoes extends javax.swing.JFrame {

    /**
     * Creates new form movimentacoes
     */
    
    private String perfil;
    
    public movimentacoes(String perfil) {
        initComponents();
        
        this.perfil=perfil;
        
        txt_movimentacoesTipo.setText("Entrada / Saida / Outro");
        txt_movimentacoesTipo.setForeground(Color.BLACK);
        
        txt_movimentacoesProduto.setText("Insira o nome do produto movimentado");
        txt_movimentacoesProduto.setForeground(Color.BLACK);

        txt_movimentacoesQuantidade.setText("Insira a quantidade movimentada");
        txt_movimentacoesQuantidade.setForeground(Color.BLACK);
                
        txt_movimentacoesData.setText("Data da movimentação ex:01/03/2025");
        txt_movimentacoesData.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_movimentacoesTipo = new javax.swing.JTextField();
        txt_movimentacoesProduto = new javax.swing.JTextField();
        txt_movimentacoesQuantidade = new javax.swing.JTextField();
        txt_movimentacoesData = new javax.swing.JTextField();
        btn_movimentacoesRegistrar = new javax.swing.JButton();
        btn_movimentacoesCancel = new javax.swing.JButton();
        btn_movimentacoesVoltar = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("MOVIMENTAÇÕES");

        jLabel2.setText("TIPO DE MOVIMENTAÇÃO:");

        jLabel3.setText("PRODUTO:");

        jLabel4.setText("QUANTIDADE:");

        jLabel5.setText("DATA:");

        txt_movimentacoesTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_movimentacoesTipoFocusLost(evt);
            }
        });
        txt_movimentacoesTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_movimentacoesTipoMousePressed(evt);
            }
        });

        txt_movimentacoesProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_movimentacoesProdutoFocusLost(evt);
            }
        });
        txt_movimentacoesProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_movimentacoesProdutoMousePressed(evt);
            }
        });

        txt_movimentacoesQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_movimentacoesQuantidadeFocusLost(evt);
            }
        });
        txt_movimentacoesQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_movimentacoesQuantidadeMousePressed(evt);
            }
        });

        txt_movimentacoesData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_movimentacoesDataFocusLost(evt);
            }
        });
        txt_movimentacoesData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_movimentacoesDataMousePressed(evt);
            }
        });

        btn_movimentacoesRegistrar.setBackground(new java.awt.Color(0, 255, 30));
        btn_movimentacoesRegistrar.setText("REGISTRAR");
        btn_movimentacoesRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_movimentacoesRegistrarActionPerformed(evt);
            }
        });

        btn_movimentacoesCancel.setBackground(new java.awt.Color(255, 0, 0));
        btn_movimentacoesCancel.setText("CANCELAR");

        btn_movimentacoesVoltar.setBackground(new java.awt.Color(0, 200, 0));
        btn_movimentacoesVoltar.setText("VOLTAR");
        btn_movimentacoesVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_movimentacoesVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_movimentacoesRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btn_movimentacoesCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_movimentacoesTipo)
                                    .addComponent(txt_movimentacoesProduto)
                                    .addComponent(txt_movimentacoesQuantidade)
                                    .addComponent(txt_movimentacoesData, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btn_movimentacoesVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_movimentacoesTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_movimentacoesProduto)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_movimentacoesQuantidade)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_movimentacoesData)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_movimentacoesCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_movimentacoesRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btn_movimentacoesVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_movimentacoesRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_movimentacoesRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_movimentacoesRegistrarActionPerformed

    private void btn_movimentacoesVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_movimentacoesVoltarActionPerformed
        menuView menu = new menuView(this.perfil);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_movimentacoesVoltarActionPerformed

    private void txt_movimentacoesTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_movimentacoesTipoFocusLost
        if (txt_movimentacoesTipo.getText().isEmpty()) {
            txt_movimentacoesTipo.setText("Entrada / Saida / Outro");
            txt_movimentacoesTipo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesTipoFocusLost

    private void txt_movimentacoesTipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_movimentacoesTipoMousePressed
        if (txt_movimentacoesTipo.getText().equals("Entrada / Saida / Outro")) {
            txt_movimentacoesTipo.setText("");
            txt_movimentacoesTipo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesTipoMousePressed

    private void txt_movimentacoesProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_movimentacoesProdutoFocusLost
        if (txt_movimentacoesProduto.getText().isEmpty()) {
            txt_movimentacoesProduto.setText("Insira o nome do produto movimentado");
            txt_movimentacoesProduto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesProdutoFocusLost

    private void txt_movimentacoesProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_movimentacoesProdutoMousePressed
        if (txt_movimentacoesProduto.getText().equals("Insira o nome do produto movimentado")) {
            txt_movimentacoesProduto.setText("");
            txt_movimentacoesProduto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesProdutoMousePressed

    private void txt_movimentacoesQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_movimentacoesQuantidadeFocusLost
        if (txt_movimentacoesQuantidade.getText().isEmpty()) {
            txt_movimentacoesQuantidade.setText("Insira a quantidade movimentada");
            txt_movimentacoesQuantidade.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesQuantidadeFocusLost

    private void txt_movimentacoesQuantidadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_movimentacoesQuantidadeMousePressed
        if (txt_movimentacoesQuantidade.getText().equals("Insira a quantidade movimentada")) {
            txt_movimentacoesQuantidade.setText("");
            txt_movimentacoesQuantidade.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesQuantidadeMousePressed

    private void txt_movimentacoesDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_movimentacoesDataFocusLost
        if (txt_movimentacoesData.getText().isEmpty()) {
            txt_movimentacoesData.setText("Data da movimentação ex:01/03/2025");
            txt_movimentacoesData.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesDataFocusLost

    private void txt_movimentacoesDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_movimentacoesDataMousePressed
        if (txt_movimentacoesData.getText().equals("Data da movimentação ex:01/03/2025")) {
            txt_movimentacoesData.setText("");
            txt_movimentacoesData.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesDataMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movimentacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movimentacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movimentacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movimentacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_movimentacoesCancel;
    private javax.swing.JButton btn_movimentacoesRegistrar;
    private javax.swing.JButton btn_movimentacoesVoltar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_movimentacoesData;
    private javax.swing.JTextField txt_movimentacoesProduto;
    private javax.swing.JTextField txt_movimentacoesQuantidade;
    private javax.swing.JTextField txt_movimentacoesTipo;
    // End of variables declaration//GEN-END:variables
}
